config/routes.rb
Rails.application.routes.draw do
  get 'settings/dashboard'
  get 'settings/insertaes'

  devise_for :users
  resources :contact_types
  resources :contacts
  resources :common_names
  resources :pictures
  resources :user_types
  resources :birds
  resources :kinds do
    collection { post :import }
  end
  resources :beak_types
  resources :beak_types
  resources :sizes
  resources :zones
  resources :colors
  resources :quantity_eggs
  resources :species
  resources :genders
  resources :families
  resources :sub_orders
  resources :orders
  resources :users do
    resources :people
  end
  root 'birds#index'

end

app/models/setting.rb
class Setting < ActiveRecord::Base

  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |kind|
        csv << kind.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  load_and_authorize_resource

  def dashboard; end

  def insertaes
    @birds = Bird.all
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/dashboard.html.erb
<%= render 'layouts/user_header_menu' %>

<div class="row">

  <div class="columns large-3">
    <%= link_to kinds_path do %>
      <div class="panel callout columns large-3 text-center radius full-width-table">
        Clases
        <h3><%= Kind.count %></h3>
      </div>
    <% end %>
  </div>

  <div class="columns large-3">
    <%= link_to orders_path do %>
      <div class="panel callout columns large-3 text-center radius full-width-table">
        Ordenes
        <h3> <%= Order.count %> </h3>
      </div>
    <% end %>
  </div>

  <div class="columns large-3">
    <%= link_to sub_orders_path do %>
      <div class="panel callout columns large-3 text-center radius full-width-table">
        Subordenes
        <h3><%= SubOrder.count %> </h3>
      </div>
    <% end %>
  </div>

  <div class="columns large-3">
    <%= link_to families_path do %>
      <div class="panel callout columns large-3 text-center radius full-width-table">
        Familias
        <h3><%= Family.count %> </h3>
      </div>
    <% end %>
  </div>

  <div class="columns large-3">
    <%= link_to genders_path do %>
      <div class="panel callout columns large-3 text-center radius full-width-table">
        Géneros
        <h3><%= Gender.count %> </h3>
      </div>
    <% end %>
  </div>

  <div class="columns large-3">
    <%= link_to species_index_path do %>
      <div class="panel callout columns large-3 text-center radius full-width-table">
        Especies
        <h3><%= Species.count %> </h3>
      </div>
    <% end %>
  </div>

  <div class="columns large-3">
    <%= link_to quantity_eggs_path do %>
      <div class="panel callout columns large-3 text-center radius full-width-table">
        Cantidad de Huevos
        <h3><%= QuantityEgg.count %></h3>
      </div>
    <% end %>
  </div>

  <div class="columns large-3">
    <%= link_to colors_path do %>
      <div class="panel callout columns large-3 text-center radius full-width-table">
        Colores
        <h3><%= Color.count %> </h3>
      </div>
    <% end %>
  </div>

  <div class="columns large-3">
    <%= link_to zones_path do %>
      <div class="panel callout columns large-3 text-center radius full-width-table">
        Zonas
        <h3><%= Zone.count %> </h3>
      </div>
    <% end %>
  </div>

  <div class="columns large-3">
    <%= link_to beak_types_path do %>
      <div class="panel callout columns large-3 text-center radius full-width-table">
        Tipos de Pico
        <h3><%= BeakType.count %> </h3>
      </div>
    <% end %>
  </div>

  <div class="columns large-3">
    <%= link_to sizes_path do %>
      <div class="panel callout columns large-3 text-center radius full-width-table">
        Tamaños
        <h3><%= Size.count %> </h3>
      </div>
    <% end %>
  </div>

  <div class="columns large-3">
    <%= link_to common_names_path do %>
      <div class="panel callout columns large-3 text-center radius full-width-table">
        Nombres Comunes
        <h3><%= CommonName.count %></h3>
      </div>
    <% end %>
  </div>
</div>

app/views/settings/insertaes.html.erb
<%= render "layouts/user_header_menu" %>

<div class="row">
  <p id="notice"><%= notice %></p>
  <p>Lista de Aves Inciertas</p>
</div>

<div class="row">
  <div class="columns small-4">
    <div class="row uncollapsed">
      <span class="prefix button success">Filtrar</span>
    </div>
  </div>
  <div class="columns small-8">
    <div class="row uncollapsed">
      <input id="searchbox" type="text"></input>
    </div>
  </div>
</div>

<% @birds.incertae_sedis.each do |bird| %>
  <%= link_to bird_path(bird) do %>
    <div class="row panel callout collaborator-datarow">

      <div class="columns large-3">
        <td><%= image_tag('https://s-media-cache-ak0.pinimg.com/236x/46/88/65/46886577309967ec698ffe37fb800b78.jpg') %></td>
      </div>

      <div class="columns large-6 collaborator-fullname">
        <div class="columns large-5">
          <td><strong>Nombre Común:</strong><%= common_name(bird).name %></td><br/>
          <td><strong>Género:</strong><%= gender(bird).name %></td><br/>
          <td><strong>Especie:</strong><%= species(bird).name %></td><br/>
        </div>
        <div class="columns large-7">
          <td><strong>Tipo de Pico:</strong><%= beak(bird).name %></td><br/>
          <td><strong>Tamaño:</strong><%= size(bird).description %></td><br/>
          <td><strong>Cantidad de Huevos:</strong><%= egg(bird).description %></td><br/>
        </div>

      </div>

      <div class="columns large-3">
        <td><%= bird.description %></td>
      </div>
    </div>
  <% end %>
<% end %>