config/routes.rb
Rails.application.routes.draw do
  get 'settings/dashboard'
  get 'settings/insertaes'

  devise_for :users
  resources :contact_types
  resources :contacts
  resources :common_names
  resources :pictures
  resources :user_types
  resources :birds
  resources :kinds do
    collection { post :import }
  end
  resources :beak_types
  resources :beak_types
  resources :sizes
  resources :zones
  resources :colors
  resources :quantity_eggs
  resources :species
  resources :genders
  resources :families
  resources :sub_orders
  resources :orders
  resources :users do
    resources :people
  end
  root 'birds#index'

end

app/controllers/contact_types_controller.rb
class ContactTypesController < ApplicationController
  load_and_authorize_resource
  before_action :set_contact_type, only: [:show, :edit, :update, :destroy]

  # GET /contact_types
  # GET /contact_types.json
  def index
    @contact_types = ContactType.all
    respond_to do |f|
      f.html
      f.csv { render text: @contact_types.to_csv }
      f.xls
    end
  end

  # GET /contact_types/1
  # GET /contact_types/1.json
  def show
  end

  # GET /contact_types/new
  def new
    @contact_type = ContactType.new
  end

  # GET /contact_types/1/edit
  def edit
  end

  # POST /contact_types
  # POST /contact_types.json
  def create
    @contact_type = ContactType.new(contact_type_params)

    respond_to do |format|
      if @contact_type.save
        format.html { redirect_to @contact_type, notice: 'Contact type was successfully created.' }
        format.json { render :show, status: :created, location: @contact_type }
      else
        format.html { render :new }
        format.json { render json: @contact_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_types/1
  # PATCH/PUT /contact_types/1.json
  def update
    respond_to do |format|
      if @contact_type.update(contact_type_params)
        format.html { redirect_to @contact_type, notice: 'Contact type was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact_type }
      else
        format.html { render :edit }
        format.json { render json: @contact_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_types/1
  # DELETE /contact_types/1.json
  def destroy
    @contact_type.destroy
    respond_to do |format|
      format.html { redirect_to contact_types_url, notice: 'Contact type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_type
      @contact_type = ContactType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_type_params
      params.require(:contact_type).permit(:name)
    end
end

app/views/contact_types/_form.html.erb
<%= simple_form_for(@contact_type) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/contact_types/edit.html.erb
<p>Editing Contact Type</p>

<%= render 'form' %>

<%= link_to 'Show', @contact_type %> |
<%= link_to 'Back', contact_types_path %>

app/views/contact_types/index.html.erb
<%= render 'layouts/user_header_menu' %>
<p id="notice"><%= notice %></p>

<p>Listing Contact Types</p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_types.each do |contact_type| %>
      <tr>
        <td><%= contact_type.name %></td>
        <td><%= link_to 'Show', contact_type %></td>
        <td><%= link_to 'Edit', edit_contact_type_path(contact_type) %></td>
        <td><%= link_to 'Destroy', contact_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact type', new_contact_type_path %>

app/views/contact_types/new.html.erb
<p>New Contact Type</p>

<%= render 'form' %>

<%= link_to 'Back', contact_types_path %>

app/views/contact_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact_type.name %>
</p>

<%= link_to 'Edit', edit_contact_type_path(@contact_type) %> |
<%= link_to 'Back', contact_types_path %>