config/routes.rb
Rails.application.routes.draw do
  get 'settings/dashboard'
  get 'settings/insertaes'

  devise_for :users
  resources :contact_types
  resources :contacts
  resources :common_names
  resources :pictures
  resources :user_types
  resources :birds
  resources :kinds do
    collection { post :import }
  end
  resources :beak_types
  resources :beak_types
  resources :sizes
  resources :zones
  resources :colors
  resources :quantity_eggs
  resources :species
  resources :genders
  resources :families
  resources :sub_orders
  resources :orders
  resources :users do
    resources :people
  end
  root 'birds#index'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_many :picture_by_beak_types
  has_many :beak_types, through: :picture_by_beak_types

  has_many :picture_by_users
  has_many :users, through: :picture_by_users

  has_many :picture_by_birds
  has_many :birds, through: :picture_by_birds

  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |kind|
        csv << kind.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  load_and_authorize_resource
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
    respond_to do |f|
      f.html
      f.csv { render text: @pictures.to_csv }
      f.xls
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:url, :name)
    end
end

app/views/pictures/_form.html.erb
<%= simple_form_for(@picture) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :url %>
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<p>Editing Picture</p>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<%= render 'layouts/user_header_menu' %>
<p id="notice"><%= notice %></p>

<p>Listing Pictures</p>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.url %></td>
        <td><%= picture.name %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<p>New Picture</p>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @picture.url %>
</p>

<p>
  <strong>Name:</strong>
  <%= @picture.name %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>