config/routes.rb
Rails.application.routes.draw do
  get 'settings/dashboard'
  get 'settings/insertaes'

  devise_for :users
  resources :contact_types
  resources :contacts
  resources :common_names
  resources :pictures
  resources :user_types
  resources :birds
  resources :kinds do
    collection { post :import }
  end
  resources :beak_types
  resources :beak_types
  resources :sizes
  resources :zones
  resources :colors
  resources :quantity_eggs
  resources :species
  resources :genders
  resources :families
  resources :sub_orders
  resources :orders
  resources :users do
    resources :people
  end
  root 'birds#index'

end

app/models/sub_order.rb
class SubOrder < ActiveRecord::Base
  belongs_to :order
  has_one :family

  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |kind|
        csv << kind.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/sub_orders_controller.rb
class SubOrdersController < ApplicationController
  load_and_authorize_resource
  before_action :set_sub_order, only: [:show, :edit, :update, :destroy]

  # GET /sub_orders
  # GET /sub_orders.json
  def index
    @sub_orders = SubOrder.all
  end

  # GET /sub_orders/1
  # GET /sub_orders/1.json
  def show
  end

  # GET /sub_orders/new
  def new
    @sub_order = SubOrder.new
  end

  # GET /sub_orders/1/edit
  def edit
  end

  # POST /sub_orders
  # POST /sub_orders.json
  def create
    @sub_order = SubOrder.new(sub_order_params)

    respond_to do |format|
      if @sub_order.save
        format.html { redirect_to @sub_order, notice: 'Sub order was successfully created.' }
        format.json { render :show, status: :created, location: @sub_order }
      else
        format.html { render :new }
        format.json { render json: @sub_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_orders/1
  # PATCH/PUT /sub_orders/1.json
  def update
    respond_to do |format|
      if @sub_order.update(sub_order_params)
        format.html { redirect_to @sub_order, notice: 'Sub order was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_order }
      else
        format.html { render :edit }
        format.json { render json: @sub_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_orders/1
  # DELETE /sub_orders/1.json
  def destroy
    @sub_order.destroy
    respond_to do |format|
      format.html { redirect_to sub_orders_url, notice: 'Sub order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_order
      @sub_order = SubOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_order_params
      params.require(:sub_order).permit(:name, :order_id)
    end
end

app/views/sub_orders/_form.html.erb
<%= simple_form_for(@sub_order) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :order_id, collection: Order.all.map { |order| [order.name, order.id] }%>
  </div>

  <div class="form-actions">
    <%= f.button :submit,"#{action_name == 'new' ? 'Crear' : 'Actualizar' }" , class: 'tiny button success round right'  %>
    <%= link_to 'Cancelar', sub_orders_path, class: 'tiny button alert round left'  %>
  </div>
<% end %>

app/views/sub_orders/edit.html.erb
<%= render 'layouts/user_header_menu' %>
<div class="row">
  <div class="columns large-4 large-centered">
    <p>Editar Suborden</p>

    <%= render 'form' %>
  </div>
</div>

app/views/sub_orders/index.html.erb
<%= render 'layouts/user_header_menu' %>
<div class="row">
  <div class="columns large-4 large-centered">
    <p id="notice"><%= notice %></p>

    <p>
      Exportar:
      <%= link_to "CSV", sub_orders_path(format: :csv), class: "exportation-link" %> |
      <%= link_to "Excel", sub_orders_path(format: :xls), class: "exportation-link" %>
    </p>

    <p>Lista de Subordenes</p>

    <table class="full-width-table">
      <thead>
        <tr>
          <th>Orden</th>
          <th>Nombre</th>
          <th colspan="3">Opciones</th>
        </tr>
      </thead>

      <tbody>
        <% @sub_orders.each do |sub_order| %>
          <tr>
            <td><%= sub_order.order.name %></td>
            <td><%= sub_order.name %></td>
            <td><%= link_to 'Editar', edit_sub_order_path(sub_order) %></td>
            <td><%= link_to 'Eliminar', sub_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Nuevo Suborden', new_sub_order_path, class: 'tiny round button right success' %>
  </div>
</div>

app/views/sub_orders/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
xmlns:html="http://www.w3.org/TR/REC-html40">
<Worksheet ss:Name="Subordenes">
<Table>
<Row>
<Cell><Data ss:Type="String">Orden</Data></Cell>
<Cell><Data ss:Type="String">Nombre</Data></Cell>
</Row>
<% @sub_orders.each do |o| %>
  <Row>
  <Cell><Data ss:Type="String"><%= o.order.name %></Data></Cell>
  <Cell><Data ss:Type="String"><%= o.name %></Data></Cell>
  </Row>
<% end %>
</Table>
</Worksheet>
</Workbook>

app/views/sub_orders/new.html.erb
<%= render 'layouts/user_header_menu' %>
<div class="row">
  <div class="columns large-4 large-centered">
    <p>Nuevo Suborden</p>

    <%= render 'form' %>
  </div>
</div>

app/views/sub_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sub_order.name %>
</p>

<p>
  <strong>Order:</strong>
  <%= @sub_order.order.name %>
</p>

<%= link_to 'Edit', edit_sub_order_path(@sub_order) %> |
<%= link_to 'Back', sub_orders_path %>